### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by skull-squadron** [adamfairhead/webicons#16]
Should be pretty easy to turn into a cocoapod, usable by rubymotion and objective-c.

https://github.com/CocoaPods/CocoaPods/wiki/The-podspec-format

**Comment by skull-squadron** [comment]
https://github.com/steakknife/FCWebicons-cocoapod

Not yet a real cocoapod, but a friend of mine has commit access... i'll check on submission requirements.

**Comment by adamfairhead** [comment]
Very cool, @steakknife. It's awesome to see the fc webicons increase their reach onto other platforms. Nice work!

**Comment by skull-squadron** [comment]
Minor roadblock, been busier lately.

https://github.com/steakknife/FCWebicons-cocoapod/issues/3

**Comment by skull-squadron** [comment]
If anyone wants to use webicons on iOS, just use libsvg-ios.  Works flawlessly.
