### ISSUE TITLE
no-svg File Names Without .png Extension?

### ISSUE THREAD

**Issue by trnelson** [adamfairhead/webicons#20]
In the code below, shouldn't the no-svg icons have a file extension (.png)? I couldn't get the code to work without it, though may have been doing it wrong.

```
.no-svg .webicon.f500px.large {
  background: url("webicons/webicon-f500px"); }
```

**Comment by adamfairhead** [comment]
Oh, fancy. That slipped through. Fixed!

**Comment by trnelson** [comment]
Awesome, thanks @adamfairhead! Very prompt and I appreciate the fix!

**Comment by adamfairhead** [comment]
My pleasure @trnelson!
