### ISSUE TITLE
Icons appear blurry?

### ISSUE THREAD

**Issue by ghost** [adamfairhead/webicons#8]
Hi,

Firstly, they're great, so thanks a lot. However just trying to work out why the icons on both the example page on the Zurb site and also the site I've implemented them on look blurry on my Samsung Galaxy S3, using Chrome. It definitely supports SVG (did .svg { background:red; } and entire site went red).

Any ideas what might be causing this?

Thanks,

**Comment by ghost** [comment]
Just had a quick check, this issue is only present in Chrome. The following browsers worked perfectly:

Firefox for Android,
Webkit Android (default),
Opera Mobile

So it's likely a bug with Chrome, but a fix would be nice.

**Comment by adamfairhead** [comment]
Yeah, for sure. I'd like to get my hands on a SS Galaxy S3 to see this problem. Any chance of a screenshot, in the mean time?

**Comment by jaredmcateer** [comment]
Here's some screen shots from my Nexus 4

http://i.imgur.com/Tu8X32s.png
http://i.imgur.com/ZkhW9PY.png

**Comment by ghost** [comment]
I think I've tracked down the actual bug:

http://code.google.com/p/chromium/issues/detail?id=161982

Looks like it won't be long before Chrome for Android updates and this will no longer be an issue.

**Comment by adamfairhead** [comment]
Perfect. This had me stumped!
